import { useState } from 'react';

import { StyleSheet, View } from 'react-native';

import { type GateChallenge, isGateAnswerCorrect } from '@/entities/settings';

import { SPACING } from '@/shared/constants';
import { useTranslation } from '@/shared/i18n';
import { Card, Input, Screen, Text } from '@/shared/ui';

// ═══════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════

interface ParentGateProps {
  /** The question being asked. Regenerated by the screen after a wrong try. */
  challenge: GateChallenge;
  /** Raised once the product is typed correctly. */
  onPass: () => void;
  /** Asks the screen for a fresh question after a wrong answer. */
  onMiss: () => void;
}

// ═══════════════════════════════════════════
// MAIN COMPONENT
// ═══════════════════════════════════════════

/**
 * The arithmetic barrier — 2.5.12, docs/parents.md.
 *
 * A multiplication rather than a PIN: there is nothing to forget and nothing to
 * store. A wrong answer only clears the field — no lockout, no timer, no
 * frightening wording, because this stops a child wandering in rather than
 * defending an account (there is nothing behind it worth stealing,
 * docs/privacy.md).
 */
export const ParentGate = ({ challenge, onPass, onMiss }: ParentGateProps) => {
  const { t } = useTranslation();
  const [typed, setTyped] = useState('');

  const handleChange = (next: string) => {
    setTyped(next);

    if (isGateAnswerCorrect(challenge, next)) {
      onPass();
      return;
    }

    // Only a full-width answer counts as a try: clearing the field on every
    // keystroke would make a two-digit product impossible to type.
    if (next.length >= String(challenge.answer).length) {
      setTyped('');
      onMiss();
    }
  };

  return (
    <Screen gap="three" isTabBarVisible={false}>
      <Screen.Header>
        <Screen.Back />
        <Screen.Heading>
          <Screen.Title>{t('parents.gate.title')}</Screen.Title>
        </Screen.Heading>
      </Screen.Header>

      <Card tone="surfaceSoft">
        <Card.Content style={styles.content}>
          <Text variant="title" style={styles.question}>
            {t('parents.gate.question', {
              left: challenge.left,
              right: challenge.right,
            })}
          </Text>

          <Input
            value={typed}
            onChangeText={handleChange}
            keyboardType="number-pad"
            maxLength={2}
            autoFocus
            accessibilityLabel={t('parents.gate.question', {
              left: challenge.left,
              right: challenge.right,
            })}
            hint={t('parents.gate.hint')}
            containerStyle={styles.field}
          />
        </Card.Content>
      </Card>

      <View style={styles.note}>
        <Text variant="small" themeColor="textSecondary">
          {t('parents.gate.note')}
        </Text>
      </View>
    </Screen>
  );
};

// ═══════════════════════════════════════════
// STYLES
// ═══════════════════════════════════════════

const styles = StyleSheet.create({
  content: {
    alignItems: 'center',
    gap: SPACING.three,
  },
  field: {
    maxWidth: 140,
  },
  note: {
    paddingHorizontal: SPACING.two,
  },
  question: {
    textAlign: 'center',
  },
});

export type { ParentGateProps };
