import { useRef, useState } from 'react';

import { Pressable, StyleSheet, TextInput, View } from 'react-native';

import type { GateChallenge } from '@/entities/settings';

import { FONTS, SPACING } from '@/shared/constants';
import { useTheme } from '@/shared/hooks';
import { useTranslation } from '@/shared/i18n';
import { Screen, Text } from '@/shared/ui';

import { applyGateInput } from '../lib';

import { Terminal } from './terminal';

// ═══════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════

interface ParentGateProps {
  /** The question being asked. Regenerated by the screen after a wrong try. */
  challenge: GateChallenge;
  /** Raised once the product is typed correctly. */
  onPass: () => void;
  /** Asks the screen for a fresh question after a wrong answer. */
  onMiss: () => void;
}

// ═══════════════════════════════════════════
// MAIN COMPONENT
// ═══════════════════════════════════════════

/**
 * The arithmetic barrier — 2.5.12, docs/parents.md.
 *
 * Dressed as the service terminal of the scene's AI monitor, but it behaves
 * exactly like before: a multiplication rather than a PIN, nothing to forget
 * and nothing to store. A wrong answer only clears the field and prints a calm
 * line — no lockout, no attempt counter, no "warning", because this stops a
 * child wandering in rather than defending an account (docs/privacy.md). The
 * retro-terminal reference is borrowed for the look only, never its threats.
 */
export const ParentGate = ({ challenge, onPass, onMiss }: ParentGateProps) => {
  const { t } = useTranslation();
  const theme = useTheme();
  const inputRef = useRef<TextInput>(null);
  const [typed, setTyped] = useState('');
  const [isMissed, setIsMissed] = useState(false);

  const question = t('parents.gate.question', {
    left: challenge.left,
    right: challenge.right,
  });

  const handleChange = (next: string) => {
    const result = applyGateInput(challenge, next);
    setTyped(result.typed);
    setIsMissed(result.isMissed);

    if (result.didPass) {
      onPass();
      return;
    }

    if (result.didMiss) {
      onMiss();
    }
  };

  return (
    <Screen gap="three" variant="arcadeDpad">
      <Screen.Header>
        <Screen.Back tone="arcadeScreen" color="arcadeLcd" />
        <Screen.Heading>
          <Screen.Title themeColor="arcadeLcd" style={styles.title}>
            {t('parents.gate.title')}
          </Screen.Title>
        </Screen.Heading>
      </Screen.Header>

      <Terminal label={t('parents.terminal.label')}>
        <Terminal.Line isPrompt order={0}>
          {t('parents.gate.bootAccess')}
        </Terminal.Line>
        <Terminal.Line isPrompt tone="dim" order={1}>
          {t('parents.gate.subtitle')}
        </Terminal.Line>

        <Terminal.Rule />

        {/* The whole row focuses the field: a thumb aimed at the sum still
            reaches the keyboard, not only a 2-digit-wide box. */}
        <Pressable
          onPress={() => inputRef.current?.focus()}
          style={styles.sum}
          accessible={false}
        >
          <Text
            themeColor="arcadeLcd"
            style={styles.sumText}
            importantForAccessibility="no"
            accessibilityElementsHidden
          >
            {`${challenge.left} × ${challenge.right} =`}
          </Text>

          <TextInput
            ref={inputRef}
            value={typed}
            onChangeText={handleChange}
            keyboardType="number-pad"
            maxLength={2}
            autoFocus
            caretHidden
            selectionColor={theme.arcadeLcd}
            placeholder="__"
            placeholderTextColor={theme.arcadeLcdDim}
            accessibilityLabel={question}
            accessibilityHint={t('parents.gate.prompt')}
            style={[
              styles.answer,
              { borderColor: theme.arcadeLcdDim, color: theme.arcadeLcd },
            ]}
          />

          <Terminal.Cursor />
        </Pressable>

        <View
          style={styles.feedback}
          accessibilityLiveRegion="polite"
          accessibilityRole="text"
        >
          {isMissed ? (
            <Terminal.Line isPrompt tone="alert">
              {t('parents.gate.miss')}
            </Terminal.Line>
          ) : (
            <Terminal.Line isPrompt tone="dim">
              {t('parents.gate.prompt')}
            </Terminal.Line>
          )}
        </View>
      </Terminal>

      <View style={styles.note}>
        <Text variant="small" themeColor="arcadeDpadFace">
          {t('parents.gate.note')}
        </Text>
      </View>
    </Screen>
  );
};

// ═══════════════════════════════════════════
// STYLES
// ═══════════════════════════════════════════

const styles = StyleSheet.create({
  answer: {
    borderBottomWidth: 2,
    fontFamily: FONTS.mono,
    fontSize: 32,
    lineHeight: 40,
    minWidth: 64,
    paddingHorizontal: SPACING.one,
    paddingVertical: SPACING.one,
    textAlign: 'center',
  },
  feedback: {
    justifyContent: 'center',
    minHeight: 48,
  },
  note: {
    paddingHorizontal: SPACING.two,
  },
  sum: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING.two,
    minHeight: 64,
  },
  sumText: {
    fontFamily: FONTS.mono,
    fontSize: 32,
    lineHeight: 40,
  },
  title: {
    fontFamily: FONTS.mono,
  },
});

export type { ParentGateProps };
