/**
 * The slice's logic and vocabulary. The rig has an entry point of its own,
 * `@/entities/pet/ui`, because pulling a React component through here would
 * drag react-native into the node test runner, which is how `entities/user`
 * reads the appearance tuples.
 */
export type {
  GrowthFacts,
  GrowthProgress,
  GrowthRule,
  PetFills,
  PetInteractionKind,
  PetNameStatus,
  PetReaction,
  PetRig,
  PetSkinLayer,
  PetZone,
} from './lib';
export {
  anchorPoint,
  anchorsFor,
  appearanceFor,
  assertTraitsContent,
  easePetAxes,
  easeTowards,
  emotionFor,
  GROWTH_RULES,
  getTraitById,
  growPet,
  isPetNameValid,
  lerpPose,
  listTraits,
  moodFor,
  needDecayFor,
  normalizePetName,
  PET_EASE_RATE,
  PET_MOOD_HIGH,
  PET_MOOD_LOW,
  PET_NAME_MAX_LENGTH,
  PET_NAME_MIN_LENGTH,
  POSE_NEUTRAL,
  poseFor,
  priceFor,
  progressToNextStage,
  reactionFor,
  rigFor,
  silhouetteFor,
  skinFor,
  skinLayerFor,
  stageFor,
  validatePetName,
  zoneAt,
} from './lib';
export type {
  AnimationKey,
  EmotionKey,
  PetAnchor,
  PetAnchors,
  PetAppearance,
  PetAxes,
  PetCoatPattern,
  PetColor,
  PetEarShape,
  PetMood,
  PetMoodAxis,
  PetMoodCauses,
  PetMoodName,
  PetPattern,
  PetPatternKind,
  PetPatternMarks,
  PetPose,
  PetReason,
  PetSilhouette,
  PetSkin,
  PetSpecies,
  PetStage,
  PetTailShape,
  TraitContent,
  TraitsFile,
} from './model';
export {
  EMOTION_KEYS,
  EMOTIONS,
  FUR_PALETTE,
  getEmotion,
  PET_COLORS,
  PET_MOOD_NAMES,
  PET_PATTERNS,
  PET_REASONS,
  PET_SPECIES,
  PET_STAGES,
} from './model';
