// ═══════════════════════════════════════════
// SPRITES
// ═══════════════════════════════════════════

/** The robot dog, whole and in parts, and the faces it pulls. */
export const CHARACTER_SPRITES = {
  dogHead: [
    '................',
    '..kk........kk..',
    '..kuk......kuk..',
    '..ktk......ktk..',
    '..ktk......ktk..',
    '..kkkkkkkkkkkk..',
    '.kttttttttttttk.',
    '.ktkkkkkkkkkkTk.',
    '.ktkaaaaaaaakTk.',
    '.ktkaYaaaaaakTk.',
    '.ktkkkkkkkkkkTk.',
    '.kttuuttttuTTTk.',
    '.kTTTTTTTTTTTTk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  dogBody: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '...kUuUuUuUuk...',
    '.kkkkkkkkkkkkkk.',
    '.kttttttttttttk.',
    '.ktwwwwwwkttuuk.',
    '.ktwkkkkwktuuUk.',
    '.ktwwwwwwkttuTk.',
    '.kttttttttttttk.',
    '.kttuutttttttTk.',
    '.ktuUutttkkkkTk.',
    '.kttuuttkkkkkTk.',
    '.kTTTTTTTTTTTTk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  dogLegs: [
    '................',
    '..kkkk....kkkk..',
    '..kttk....kttk..',
    '..kttk....kttk..',
    '..kuTk....kuTk..',
    '.kkyykk..kkyykk.',
    '.kyyyok..kyyyok.',
    '..kook....kook..',
    '..kTTk....kTTk..',
    '..ktTk....ktTk..',
    '..kuTk....kuTk..',
    '..ktTk....ktTk..',
    '.kkkkkk..kkkkkk.',
    'kyddddk.kyddddk.',
    'kkkkkkk.kkkkkkk.',
    '................',
  ],
  dogJoy: [
    'Y...............',
    '..kk........kk.Y',
    '..kuk......kuk..',
    '..ktk......ktk..',
    '..ktk......ktk..',
    '..kkkkkkkkkkkk..',
    '.kttttttttttttk.',
    '.ktkkkkkkkkkkTk.',
    '.ktkakaaaakakTk.',
    '.ktkkakaakakkTk.',
    '.ktkkkkkkkkkkTk.',
    '.ktpkttttttkpTk.',
    '.kTTTkkkkkkTTTk.',
    '..kkkkkkkkkkkk..',
    '...Y............',
    '.............Y..',
  ],
  dogThink: [
    '......GGG.......',
    '..kk.....G..kk..',
    '..kuk...G..kuk..',
    '..ktk......ktk..',
    '..ktk...G..ktk..',
    '..kkkkkkkkkkkk..',
    '.kttttttttttttk.',
    '.ktkkkkkkkkkkTk.',
    '.ktkaaaaaaaakTk.',
    '.ktkakkaakkakTk.',
    '.ktkkkkkkkkkkTk.',
    '.kttuuttttuTTTk.',
    '.kTTTTTTTTTTTTk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  dogSide: [
    '...............kkkkkk...',
    '...............kukkuk...',
    '...............ktkktk...',
    '..............kkkkkkkkk.',
    '..............kttttttTk.',
    '..............ktkkkkkTk.',
    '.kkkkkkkkkkkkkktkaYaakTk',
    '.kuUuUuUuUuUuUttkkkkkTk.',
    '.ktttttttttttttttttttTk.',
    '.kttuutttttuutttttttTTk.',
    '.ktuUuttttttuUuttttttTk.',
    '.kttutttttttttuttttttTk.',
    '.kTTTTTTTTTTTTTTTTTTTTk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..ktTk.ktTk..ktTk.ktTk..',
    '..kyyk.kyyk..kyyk.kyyk..',
    '..kuTk.kuTk..kuTk.kuTk..',
    '.kkddk.kddkk.kddkkkddk..',
    '.kkkkk.kkkkk.kkkkkkkkk..',
  ],
} as const;
