// ═══════════════════════════════════════════
// SPRITES
// ═══════════════════════════════════════════

/** Toys for the robot dog. Each one bought opens a puzzle picture. */
export const TOY_SPRITES = {
  puzzle: [
    '................',
    '.....kkk........',
    '....kGGGk.......',
    '....kGGgk.......',
    '.kkkkGGgkkkkk...',
    '.kGGGGGGGGGGgk..',
    '.kGwGGGGGGGGgk..',
    '.kGGGGGGGGGGgkk.',
    '..kGGGGGGGGGgGGk',
    '..kGGGGGGGGGgGgk',
    '.kkGGGGGGGGGgkk.',
    '.kGGGGGGGGGGgk..',
    '.kGGGGGGGGGGgk..',
    '.kgggggggggggk..',
    '.kkkkkkkkkkkkk..',
    '................',
  ],
  toyBall: [
    '................',
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..kwwrrrrrrrRk..',
    '.kwwrrrrrrrrrRk.',
    '.kwrrrrrrrrrrRk.',
    '.kyyyyyyyyyyyok.',
    '.kyyyyyyyyyyyok.',
    '.krrrrrrrrrrRRk.',
    '.krrrrrrrrrrRRk.',
    '.krrrrrrrrrRRRk.',
    '.kRrrrrrrrRRRRk.',
    '..kRrrrrrRRRRk..',
    '...kkRRRRRRkk...',
    '.....kkkkkk.....',
    '................',
  ],
  toyBone: [
    '................',
    '................',
    '................',
    '................',
    '..kk........kk..',
    '.kwlk......klmk.',
    '.kllkkkkkkkklmk.',
    '..kwllllllllmk..',
    '..klllllllllmk..',
    '.kllkkkkkkkklmk.',
    '.klmk......kmmk.',
    '..kk........kk..',
    '................',
    '................',
    '................',
    '................',
  ],
  toyFrisbee: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkBBBBBBBBkk..',
    '.kBwwBBBBBBBBbk.',
    'kbBBBBBBBBBBBBbk',
    'knbbbbbbbbbbbbnk',
    '.knnbbbbbbbbnnk.',
    '..kknnnnnnnnkk..',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  toyDuck: [
    '................',
    '................',
    '....kkkk........',
    '...kwyyyk.......',
    '..kyyykyyk......',
    'kkkyyyyyyk......',
    'kaaayyyyyk......',
    'kkkkyyyyk...kk..',
    '...kyyyyykkkyyk.',
    '..kyyyyyyyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    '.kyyyyoyyyyyyok.',
    '.kyyyyyooooyyok.',
    '..koyyyyyyyyok..',
    '...kkkkkkkkkk...',
    '................',
  ],
  toyYoyo: [
    '.......kk.......',
    '......kwlk......',
    '.......kk.......',
    '.......m........',
    '.......m........',
    '.......m........',
    '.....kkkkkk.....',
    '...kkvvvvvvkk...',
    '..kvwvvvvvvvVk..',
    '.kvwvvvvvvvvvVk.',
    '.kkkkkkkkkkkkkk.',
    '.kvvvvvvvvvvvVk.',
    '..kVvvvvvvvvVk..',
    '...kkVVVVVVkk...',
    '.....kkkkkk.....',
    '................',
  ],
  toyCube: [
    '................',
    '................',
    '................',
    '...kkkk..kkkk...',
    '...kBBk..kBBk...',
    '.kkkBbkkkkBbkkk.',
    '.kBBBBBBBBBBBbk.',
    '.kBwBBBBBBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kbbbbbbbbbbbnk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
} as const;
