export type { WatcherAction, WatcherId } from './model';
export {
  DEFAULT_WATCHER_ACTION,
  WATCHER_ACTIONS,
  WATCHER_CLIPS,
  WATCHER_FADE_SEC,
  WATCHER_FOCUS_ACTION,
  WATCHER_FOCUS_DISTANCE,
  WATCHER_HIDDEN_MATERIALS,
  WATCHER_IDS,
  WATCHER_PLACEMENT,
  WATCHER_UNITS_PER_METRE,
  WATCHER_YAW,
} from './model';
